### ISSUE TITLE
"no record" mode that will error on an unrecorded request

### ISSUE THREAD

**Issue by jeremyruppel** [flickr/yakbak#1]
This would be super useful on CI where we absolutely don't want to record anything new. This should have the same behavior as [vcr's record `:none` mode][1].

[1]: https://relishapp.com/vcr/vcr/v/3-0-1/docs/record-modes/none

**Comment by jeremyruppel** [comment]
Closed via #17 and released in 2.5.0. Thanks @ijpiantanida!

**Comment by rwjblue** [comment]
This can likely be closed (now that #17 is landed and released in 2.5.0).

**Comment by jeremyruppel** [comment]
Right you are, @rwjblue. Thanks!
