### ISSUE TITLE
Dynamic responsa

### ISSUE THREAD

**Issue by bassjacob** [flickr/yakbak#20]
Would you be interested in adding documentation on how to edit a yakbak response to make it dynamic?

I had a usecase where I wanted to test an API client that should cache a response if passed a flag and not otherwise, but obviously yakbak "caches" the server response anyway. So I edited the "tape" to return a dynamic response so I could test that.

If it's something you'd like to add docs for, I'm happy to write up what I did with an example so it's clear?

**Comment by jeremyruppel** [comment]
I think this would be super helpful! Maybe we should start a collection of docs/examples/recipes, perhaps something like [gulp][1] or [browserify][2] have. If you want to write up what you did and add it to a `docs` directory, I'd gladly merge it. Thanks!

[1]: https://github.com/gulpjs/gulp/tree/master/docs/recipes
[2]: https://github.com/substack/node-browserify/tree/master/example
