### ISSUE TITLE
option to create custom hash/tape names

### ISSUE THREAD

**Issue by stephenmathieson** [flickr/yakbak#29]
First off, this package is awesome! Great work here =)

I'm currently moving an enormous codebase (all [segment.com integrations](https://segment.com/catalog#integrations/all)) away from hitting 3rd party APIs in tests to use `yakbak`, but I'm hitting issues with APIs that require cache-busting query parameters (example: [google-analytics](https://github.com/segment-integrations/integration-google-analytics/blob/1.9.9/lib/classic.js#L88)).

Would you be open to a (backwards compatible) addition to the API that allows users to create their own `hash` function?

**Comment by jeremyruppel** [comment]
Totally! I think this is a great proposal. I'm going to close this and we can continue discussing over in #30.
