### ISSUE TITLE
differentiate from other libraries

### ISSUE THREAD

**Issue by NodeGuy** [flickr/yakbak#6]
It would be helpful if you add a note to your README explaining why you created a new project instead of using [Nock's record feature](https://github.com/node-nock/nock#recording) or [Node Replay](http://documentup.com/assaf/node-replay).

**Comment by jeremyruppel** [comment]
Thanks for reminding me! I wrote about this at length on [the Flickr code blog][1] but totally forgot to reference that in the README. Hopefully that article explains why I prefer this approach to monkey-patching node internals.

[1]: http://code.flickr.net/2016/04/25/introducing-yakbak-record-and-playback-http-interactions-in-nodejs/
